### ISSUE TITLE
Results on Synthetic Urban Datasets

### ISSUE THREAD

**Issue by LJ-Zhang** [matsuren/omnimvs_pytorch#3]
Thanks for your contribution!
Have you tried your implementation in Synthetic Urban Datasets? I found the result is poor with your default configurations. Can you provide a training config. file or a pretrained model on this dataset?

**Comment by matsuren** [comment]
Hi, 
Thank you for your comment. I haven't tried on Synthetic Urban Datasets yet. 
You can download a pre-trained model (ndisp=48) from [here](https://1drv.ms/u/s!Ao6oo2sMuht4tyd5tU1OS0hNjzNb?e=rez8E0). 

I think poor performance is because of the number of disparity. I can't set the number of disparity as high as the one in the paper because of lack of GPU memory.

Thanks,
